### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by crazygmr101** [Cursed-Solutions/Tanjun#110]
I haven't figured out a generic reproducible way to get this error, but tanjun will respond with `Command not found` in discord when a slash command throws an exception, which is both incorrect and unclear.

Hikari: 2.0.0.dev103 (https://github.com/hikari-py/hikari/commit/39cf4c24bff2bb687608160792b86df2d335d2d3)
Tanjun: 2.0.0a4 (https://github.com/FasterSpeeding/Tanjun/commit/e937a4b8074b6f4da567ce8cb7f459593b038ad3)

Sample code;
```py
@settings_group.with_command
@tanjun.with_str_slash_option("value", "The value to set it to")
@tanjun.with_str_slash_option("setting", "The setting to set",
                              choices=[(choice[1][3], choice[0]) for choice in DatabaseProto.VALID_SETTINGS.items()])
@tanjun.as_slash_command("set", "Set config option")
async def set_setting(ctx: tanjun.SlashContext, setting: str, value: str,
                      _db: DatabaseProto = tanjun.injected(type=DatabaseProto)):
    try:
        await _db.set_setting(ctx.author.id, setting, value)
        await ctx.respond(f"Set {DatabaseProto.VALID_SETTINGS[setting][3]} to {value}")
    except ValueError as err:
        await ctx.respond(embed=_db.error_embed("Invalid value", str(err)))
```
Stack trace: https://pastebin.com/vVJZ56wY

Discord reponse:
![image](https://user-images.githubusercontent.com/22755628/135069371-80a7b524-73b8-4ff2-b2c3-4b3e684dd767.png)

**Comment by FasterSpeeding** [comment]
There's a lot more info about this in this thread https://discord.com/channels/574921006817476608/892369488908021780

**Comment by FasterSpeeding** [comment]
Gonna close this since this behaviour can no-longer be reproduced
