### ISSUE TITLE
Add `Cooldown Checks` to Tanjun

### ISSUE THREAD

**Issue by thenishantsapkota** [Cursed-Solutions/Tanjun#136]
Cooldowns would be a handy feature to use as people like to spam commands all the time.

**Comment by FasterSpeeding** [comment]
will do, this'll likely be implemented as a standard dependency where the check just calls the dependency's interface allowing ppl to slot in their own custom impls while using the same check everywhere

**Comment by thenishantsapkota** [comment]
Any updates on this?

**Comment by FasterSpeeding** [comment]
> Any updates on this?

not yet but i'll try to get around to finishing this stuff soon, I do have code for this stashed away locally

**Comment by FasterSpeeding** [comment]
By the way #152 is a working implementation of this, in its current state it needs test coverage and documentation before it could be considered for a release

**Comment by FasterSpeeding** [comment]
A similar interface concurrency limiter might also be helpful
