### ISSUE TITLE
'_CommandBuilder' object has no attribute 'description'

### ISSUE THREAD

**Issue by zlalvani** [Cursed-Solutions/Tanjun#203]
Hello,

I'm trying to implement a basic Discord bot with slash commands. To do this, I've defined a component and a function with the slash command decorators as follows, based on the example [here](https://patchwork.systems/programming/hikari-discord-bot/introduction-and-basic-bot.html):

```python
import tanjun

component = tanjun.Component()

@component.with_slash_command
@tanjun.as_slash_command("play", "Find out what your User ID is!")
async def play(ctx: tanjun.abc.Context) -> None:
    await ctx.respond(f"Hi {ctx.author.mention}! \nYour User ID is: ```{ctx.author.id}```")

loader = component.make_loader()
```

I've also got a hikari bot / tanjun client defined:

```python
bot = hikari.GatewayBot(token=CONFIG.BOT_TOKEN)

client = ( 
    tanjun.Client.from_gateway_bot(
        bot,
        mention_prefix=True,
        declare_global_commands=CONFIG.GUILD_ID if CONFIG.GUILD_ID else False
    )
)

from app.commands.play import component as play_component
client.add_component(play_component)
```

However, when I call `bot.run()`, I see an uncaught exception in the terminal, and the slash command doesn't seem to get added to my guild:
```AttributeError: '_CommandBuilder' object has no attribute 'description'```

The stacktrace says it's coming from line 807 in `_CommandBuilder.copy()`, where `self.description` is undefined:
```python
    def copy(self) -> _CommandBuilder:  # TODO: can we just del _CommandBuilder.__copy__ to go back to the default?
        builder = _CommandBuilder(self.name, self.description, self._sort_options, id=self.id)

        for option in self._options:
            builder.add_option(option)

        return builder
```

The `_CommandBuilder` constructor seems to pass its `description` param to the base class `hikari.impl.CommandBuilder` but this class doesn't seem to do anything with it, which I imagine is a bug. 

Here's the lib versions I'm running:
```
name         : hikari
version      : 2.0.0.dev106

name         : hikari-tanjun
version      : 2.3.1a1

dependencies
 - hikari >=2.0.0.dev105,<2.1.0
```

**Comment by FasterSpeeding** [comment]
The latest tanjun release isn't compatible with the latest hikari release, you'll want to target specifically hikari==2.0.0.dev105

**Comment by zlalvani** [comment]
Thanks for the quick reply. Would it be worth making a PR to pin the dependency on hikari?

**Comment by FasterSpeeding** [comment]
https://github.com/FasterSpeeding/Tanjun/pull/202 has experimental (under-documented and untested) support for hikari's latest release and its features; the plan is to have this finished and released within the next couple of days

**Comment by FasterSpeeding** [comment]
This should be fixed in the latest release
