### ISSUE TITLE
Parent attribute of subcommand objects return None when loaded their components from another module

### ISSUE THREAD

**Issue by fdnt7** [Cursed-Solutions/Tanjun#260]
When loading a component that contains commands groups (whether message or slash) from another module, the `parent` attribute of subcommand objects will returns `None`. This does not happen when such a component is initialized in the same module as where the `tanjun.Client` object is initialized; so it doesn't need to call `.load_modules(...)` and instead just adds the component from `.add_component(...)`.

Tanjun Ver. : [2.5.0a1](https://github.com/FasterSpeeding/Tanjun/compare/v2.4.3a1...v2.5.0a1)
Python Ver. : 3.10.4
Steps to reproduce:
1. make `main.py` as such
```py
import hikari as hk
import tanjun as tj
import alluka as al

TOKEN = '...'
GUILD = ...

client = (
    tj.Client.from_gateway_bot(
        bot := hk.GatewayBot(TOKEN), declare_global_commands=GUILD
    )
    .load_modules('mod1')
)


@client.with_listener(hk.StartedEvent)
async def on_started(_: hk.StartedEvent, client_: al.Injected[tj.abc.Client]):
    for groups in client_.iter_commands():
        for cmd in getattr(groups, 'commands'):
            print(cmd.parent) # prints out the parent command 


bot.run()
```
2. make `mod1.py` as such
```py
import tanjun as tj


comp = tj.Component()


@comp.with_command
@tj.as_message_command_group('group1')
async def group1(ctx: tj.abc.MessageContext):
    await ctx.respond(...)


@group1.with_command
@tj.as_message_command('subcmd1')
async def subcmd1(ctx: tj.abc.MessageContext):
    await ctx.respond('subcmd1 response')
    

group2 = comp.with_command(tj.slash_command_group('group2', "group2 desc"))


@group2.with_command
@tj.as_slash_command('subcmd2', "subcmd2 desc")
async def subcmd2(ctx: tj.abc.SlashContext):
    await ctx.respond('subcmd2 response')
    
    
loader = comp.make_loader()
```
3. run `main.py`. It prints `None` and `None`, as opposed to the expected `CommandGroup <1: ['group1']>` and `<tanjun.commands.slash.SlashCommandGroup object at 0x...>`. This happens whether importing the modules from a `pathlib.Path` object or via a string.

To reproduce the *expected* result instead, have the component and its commands defined right in `main.py`, remove the loader, and replace `.load_modules('mod1')` with `.add_component(comp)`

**Comment by fdnt7** [comment]
**Update**: As of 2.5.2a1 (Or possibly earlier), this testing code now produces the result `CommandGroup <1: ['group1']>` and `None` and also from now onwards *this issue is only for slash command groups and not message commands groups anymore*.

**Comment by FasterSpeeding** [comment]
I do plan on looking into this btw, I think i've ran into this issue with the changes I have stashed away for command Permissions V2 and will fix this with that
