### ISSUE TITLE
Add a higher level abstraction of creating and syncing commands to a specific guild

### ISSUE THREAD

**Issue by GoogolGenius** [Cursed-Solutions/Tanjun#301]
I thought it might be a nice idea to provide a way to add specific guilds per a command and easily sync to those specific guilds. 

Right now, it's more complicated because currently, Tanjun only syncs commands with `is_global=True` to guilds passed in `declare_global_commands`. There is no easy way to sync commands to a specific guild and have some commands global, etc.

Please let me know what you think of this suggestion.
Thanks!

**Comment by FasterSpeeding** [comment]
This sounds a bit unnecessary imo; declaring commands per-guild was mostly just a debug/dev feature which doesn't make sense at scale and all you need to set the commands on multiple guilds right now is something along the lines of

```py
commands = [...get_commands...]

await asyncio.gather(*(client.declare_application_commands(commands, command_ids={}, guild=guild) for guild in guilds)) 
```

And that'll handle checking if they've match the already declared commands per-guild unless you also pass `force=True`.

If you're looking for a way to get specific groups of commands other than global vs non-global then you might be asking for this maybe-TODO which has been sat around for quite a while https://github.com/FasterSpeeding/Tanjun/projects/1#card-73913473.

**Comment by GoogolGenius** [comment]
I don't remember if I opened this before backend v2 was released or not but yeah, this is probably unnecessary anyway.
