### ISSUE TITLE
Set_auto_defer does not defer with the correct flags

### ISSUE THREAD

**Issue by l3keboy** [Cursed-Solutions/Tanjun#302]
When set_auto_defer_after kicks in, it doesnt defer with the correct flags. 

Steps to reproduce:
- Set the client auto_defer_after() to 0 --> client.set_auto_defer_after(0)

```
@tanjun.as_slash_command("test_defer", "test", always_defer=True, default_to_ephemeral=True)
async def command_test(ctx):
    await ctx.respond("Done!")
```

**Comment by FasterSpeeding** [comment]
This isn't really a bug, this is just a side effect of what auto_defer == 0 means

Auto deferral is client level and the timer for it starts when the interaction is received and setting it to 0 indicates that it should be deferred during the next event loop cycle, this next cycle is likely reached when checks are run, before it's even found any matching commands with this meaning that it'll be deferred before its matched a command to set the ephemeral default. This likely isn't going to change for a long time and can be worked around by setting a small but non-zero value for the client level auto defer.
