### ISSUE TITLE
sub command group have issue

### ISSUE THREAD

**Issue by HazemMeqdad** [Cursed-Solutions/Tanjun#339]
https://github.com/FasterSpeeding/Tanjun/blob/master/examples/slash_commands.py#L55

on use a command respond "Command not found"

![image](https://user-images.githubusercontent.com/66125469/174795771-8b4a1536-9027-4d60-bb80-10954f49a012.png)

**Comment by FasterSpeeding** [comment]
Unknown interaction usually indicates that either you are running multiple instances of the bot and another instance created the initial response before this instance could or your internet/machine is too slow and the interaction timed out before it could respond (which would take 3 seconds btw) but the former is more likely if that code is what you're using

**Comment by HazemMeqdad** [comment]
on use other command i don't got this issue its only in a sub command group

**Comment by FasterSpeeding** [comment]
Yeah I can't recreate the behaviour your describing using that specific example code with the latest release, make sure you're using an up to date version of Tanjun and aren't running the bot multiple times
