### ISSUE TITLE
Passing `component=None` to edit_initial_message does not delete the component(s)

### ISSUE THREAD

**Issue by parafoxia** [Cursed-Solutions/Tanjun#59]
Using `components=[]` does as expected, but `component=None` just leaves the component there. Unsure if this happens on other methods. If this is the intended behaviour, it is incorrectly documented.

**Comment by FasterSpeeding** [comment]
Will look into this

**Comment by FasterSpeeding** [comment]
This is an upstream issue on discord's end (inconsistency between endpoints), i'll report it to Discord and if they don't change it i'll change how Hikari handles updating components since it only works on edit channel message endpoints and not edit webhook message endpoints right now

**Comment by pblan** [comment]
Any updates on this?

**Comment by FasterSpeeding** [comment]
Nope not yet, been busy with other stuff recently

**Comment by FasterSpeeding** [comment]
This should be fixed in the next hikari release
